name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: macos-latest

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper blame and history in SonarQube

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Run Build Wrapper with xcodebuild
        run: |
          build-wrapper-macosx-x86 --out-dir $BUILD_WRAPPER_OUT_DIR \
            xcodebuild -project HIDApproveSDKWrapper.xcodeproj \
                       -scheme HIDApproveSDKWrapper \
                       -sdk iphonesimulator \
                       -destination 'platform=iOS Simulator,name=iPhone 16' \
                       CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                       clean build

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
